### ISSUE TITLE
No match!

### ISSUE THREAD

**Issue by HectorSaldes** [madzadev/memory-game#1]
Hello friend, I was playing your game, when I had an issue, two cards don't match.

I let you evidences.

![image](https://user-images.githubusercontent.com/61708286/168515472-8fbacaae-e08d-42e3-a474-c80a30819db4.png)

![image](https://user-images.githubusercontent.com/61708286/168515515-7d76bec5-231e-4618-8d76-d97ed438d35e.png)

I hope your soon answer.
Greetings from Mexico 🇲🇽
(I think your portfolio is amazing!)

**Comment by madzadev** [comment]
Hello, @HectorSaldes !
Thanks for reporting, should be fixed now!
